### ISSUE TITLE
EMF-like management of collection

### ISSUE THREAD

**Issue by brice-morin** [dukeboard/kevoree-modeling-framework#10]
It would be great (to facilitate the porting of existing code) if we could do:
```java
myElement.getMyCollection().add(myOtherElement);//This exactly looks like existing client code using the EMF API.
```

instead of 
```java
myElement.addMyCollection(myOtherElement); //This does not look like EMF client code...
```

Of course, we should keep all the good properties on KMF/Kotlin collections

**Comment by dukeboard** [comment]
Deprecated, now distortable structure are synchronous, we leave EMF compatibility for API
