### ISSUE TITLE
model query in JS

### ISSUE THREAD

**Issue by ahervieu** [dukeboard/kevoree-modeling-framework#62]
The follwoing queries are not providing the same result :
```
 var res = kPCM.select("matrices[id = *]/cells[name = * windows *]");
```
```
 var res = kPCM.select("matrices[id = *]/cells[name = *windows*]");
```      
In the second query, having the * just after the word windows removes the last letter of the word windows inside the query.
Query is then interpreted as follow :
```
 var res = kPCM.select("matrices[id = *]/cells[name = *window *]");
```

**Comment by dukeboard** [comment]
Fixed in v4
