### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by StephaneMangin** [dukeboard/kevoree-modeling-framework#68]
The output : 

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.kevoree.modeling.microframework.typescript.NoJs_MainTest
Extract /home/blacknight/.nodejs/v0.10.20/node-v0.10.20-linux-x64.tar.gz START
Extract /home/blacknight/.nodejs/v0.10.20/node-v0.10.20-linux-x64.tar.gz DONE
déc. 27, 2014 1:25:14 PM NodejsExecutable start
INFOS: de.flapdoodle.embed.nodejs.NodejsConfig@66d33a
[nodejs error]
[nodejs error] undefined:4
[nodejs error]     __.prototype = b.prototype;
[nodejs error]                     ^
[nodejs error] TypeError: Cannot read property 'prototype' of undefined
[nodejs error]     at __extends (eval at <anonymous> (/home/blacknight/projects/kevoree-modeling-framework/org.kevoree.modeling.microframework.typescript/target/test-classes/MyTestRunner.js:6:98), <anonymous>:4:21)
[nodejs error]     at eval (eval at <anonymous> (/home/blacknight/projects/kevoree-modeling-framework/org.kevoree.modeling.microframework.typescript/target/test-classes/MyTestRunner.js:6:98), <anonymous>:7147:25)
[nodejs error]     at api.abs.api.abs (eval at <anonymous> (/home/blacknight/projects/kevoree-modeling-framework/org.kevoree.modeling.microframework.typescript/target/test-classes/MyTestRunner.js:6:98), <anonymous>:7156:23)
[nodejs error]     at modeling.api.modeling.api (eval at <anonymous> (/home/blacknight/projects/kevoree-modeling-framework/org.kevoree.modeling.microframework.typescript/target/test-classes/MyTestRunner.js:6:98), <anonymous>:8106:19)
[nodejs error] 
    at kevoree.modeling.kevoree.modeling (eval at <anonymous> (/home/blacknight/projects/kevoree-modeling-framework/org.kevoree.modeling.microframework.typescript/target/test-classes/MyTestRunner.js:6:98), <anonymous>:8107:15)
[nodejs error]     at org.kevoree.org.kevoree (eval at <anonymous> (/home/blacknight/projects/kevoree-modeling-framework/org.kevoree.modeling.microframework.typescript/target/test-classes/MyTestRunner.js:6:98), <anonymous>:8108:11)
[nodejs error]     at org (eval at <anonymous> (/home/blacknight/projects/kevoree-modeling-framework/org.kevoree.modeling.microframework.typescript/target/test-classes/MyTestRunner.js:6:98), <anonymous>:8109:7)
[nodejs error]     at Object.eval (eval at <anonymous> (/home/blacknight/projects/kevoree-modeling-framework/org.kevoree.modeling.microframework.typescript/target/test-classes/MyTestRunner.js:6:98), <anonymous>:8110:3)
[nodejs error]     at Object.<anonymous> (/home/blacknight/projects/kevoree-modeling-framework/org.kevoree.modeling.microframework.typescript/target/test-classes/MyTestRunner.js:6:1)
[nodejs error]     at Module._compile (module.js:456:26)
[nodejs error] 
déc. 27, 2014 1:25:14 PM de.flapdoodle.embed.process.io.file.Files forceDelete
INFOS: Could delete /tmp/extract-020cf098-5c81-4a7c-9bea-98dfa06f6e9fnode.pid
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.544 sec <<< FAILURE!
déc. 27, 2014 1:25:14 PM de.flapdoodle.embed.process.io.file.Files forceDelete
INFOS: Could delete /tmp/extract-020cf098-5c81-4a7c-9bea-98dfa06f6e9fnode
déc. 27, 2014 1:25:14 PM de.flapdoodle.embed.process.store.CachingArtifactStore removeFileSet
AVERTISSEMENT: Allready removed de.flapdoodle.embed.process.extract.ImmutableExtractedFileSet@1888ff2c for V0_10:Linux:B64, emergency shutdown?

Results :

Failed tests:   baseTest(org.kevoree.modeling.microframework.typescript.NoJs_MainTest): expected:<0> but was:<8>

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

**Comment by dukeboard** [comment]
Hello,
This issue should be fixed right now in the snapshot version. At least on our build environment similar to yours it is fixed. Can you confirme it before I do the release ?
