### ISSUE TITLE
Wrong cardinality in KMF MM generated from EMF MM

### ISSUE THREAD

**Issue by pascalpoizat** [dukeboard/kevoree-modeling-framework#69]
error:
I have a .ecore file with a 1/-1 (1..*) cardinality. It is transformed in a 1/1 cardinality in the .mm file generated from it.

environment:
.ecore file is created under Eclipse. Then copied in an IntelliJ workspace.
Right click on the .ecore file -> convert to meta model DSL.
IntelliJ IDEA 14.0.2 139.659, Dec 6th, 2014
Kevoree plugin V16

files: (should I add piece of code through Gist ?)

EMF

  <eClassifiers xsi:type="ecore:EClass" name="Workflow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" lowerBound="1" upperBound="-1"
        eType="#//WorkflowNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialNode" lowerBound="1"
        eType="#//InitialEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="finalNodes" upperBound="-1"
        eType="#//EndEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequenceFlows" upperBound="-1"
        eType="#//SequenceFlow" containment="true"/>
  </eClassifiers>

KMF

class pif.Workflow  {
    @contained
    nodes : pif.WorkflowNode
    initialNode : pif.InitialEvent
    finalNodes : pif.EndEvent[0,*]
    @contained
    sequenceFlows : pif.SequenceFlow[0,*]
}

**Comment by dukeboard** [comment]
Hello,
thanks for the bug report, I check immediately if i can reproduce.

**Comment by dukeboard** [comment]
Hi again, after a quick check in our code its quite difficult to understand how the upper bound (int value) of a reference can be null into the Ecore AST (which is used for the conversion). Can you provide us the ecore used ? By advance thanks.

**Comment by dukeboard** [comment]
I've pushed a potential fix in the version 17 of the plugin.
Can you update and confirme me the correction in V17 please ?

Thanks by advance

**Comment by pascalpoizat** [comment]
Merci François

> Le 9 janv. 2015 à 14:13, Fouquet François <notifications@github.com> a écrit :
> 
> Hello,
> thanks for the bug report, I check immediately if i can reproduce.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
Pascal Poizat
Université Paris Ouest Nanterre la Défense
LIP6 UMR 7606 CNRS
http://lip6.fr/Pascal.Poizat

**Comment by pascalpoizat** [comment]
Here you are


> Le 9 janv. 2015 à 14:22, Fouquet François <notifications@github.com> a écrit :
> 
> Hi again, after a quick check in our code its quite difficult to understand how the upper bound (int value) of a reference can be null into the Ecore AST (which is used for the conversion). Can you provide us the ecore used ? By advance thanks.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
Pascal Poizat
Université Paris Ouest Nanterre la Défense
LIP6 UMR 7606 CNRS
http://lip6.fr/Pascal.Poizat

**Comment by pascalpoizat** [comment]
I have updated the plugin (using IntelliJ update mechanism, didn’t know how to do it with github).
It seems to work (at least for the bug we found). I will check it more carefully in 7 days.

> Le 9 janv. 2015 à 15:07, Fouquet François <notifications@github.com> a écrit :
> 
> I've pushed a potential fix in the version 17 of the plugin.
> Can you update and confirme me the correction in V17 please ?
> 
> Thanks by advance
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
Pascal Poizat
Université Paris Ouest Nanterre la Défense
LIP6 UMR 7606 CNRS
http://lip6.fr/Pascal.Poizat

**Comment by dukeboard** [comment]
Ok perfect, the update process of IDEA is fine. I close this ticket.
I have modified the generation process for 1..* relationships, so it should address the problem.
If you face another issue, don't hesitate to open a ticket again.

Best Regards,
François
