### ISSUE TITLE
Feature request: Adding a function related to

### ISSUE THREAD

**Issue by electricalwind** [dukeboard/kevoree-modeling-framework#71]
It would be nice to have a function available for each object that indicate if this object is related to another given object ( e.g: in an opposite relation to know if there is a link between those two object).

**Comment by dukeboard** [comment]
Could be nice, will be introduced in 4.9.0 next version, the synchronous aspect of the method could be helpful during the promise API usage

**Comment by dukeboard** [comment]
method relationsWith on KObject with other KObject has been added since the version 4.9.0, enjoy :-)

**Comment by electricalwind** [comment]
works fine :) Thanks
