### ISSUE TITLE
JS generated model does not follow the right namespace

### ISSUE THREAD

**Issue by maxleiko** [dukeboard/kevoree-modeling-framework#74]
From Kevoree MM, you will have to create `KevoreeUniverse` from `org.KevoreeUniverse` but you expect it to be accessible from `org.kevoree.KevoreeUniverse`

**Comment by gnain** [comment]
You may want to use the <fullQualifiedName> option of the plugin.
--
Grégory NAIN, PhD
Research Associate 
Internet of Things Lab

University of Luxembourg
SnT Research Center, Office C122
4 rue Alphonse Weicker
L-2721 Luxembourg, Luxembourg
Office:+352 466644 5250
Email: gregory.nain@uni.lu

**Comment by maxleiko** [comment]
If you mean `<metaModelQualifiedName>org.kevoree</metaModelQualifiedName>`, then I did. And the issue is still there.

**Comment by gnain** [comment]
Give it a try with <metaModelQualifiedName>org.kevoree.Kevoree</metaModelQualifiedName>

**Comment by maxleiko** [comment]
Yes, it works. But that is, still, a bug.

**Comment by brice-morin** [comment]
I can feel some tension in this discussion...

**Comment by dukeboard** [comment]
No :-) design and API convergence :-)

**Comment by dukeboard** [comment]
Seems to be not a bug, in the new naming strategy the last name FQN or .mm file is the metaModel name, and so generate the associated API element names. Here org.kevoree.kevoree seems to be consistent for Java and JS so as for we test it seems to be not a bug here.

**Comment by maxleiko** [comment]
My model filename is `org.kevoree.mm`
My `pom.xml` configuration for the KMF plugin is:  

```xml
<!-- ... -->
<execution>
  <id>ModelGen</id>
    <goals>
      <goal>generate</goal>
    </goals>
    <phase>process-sources</phase>
    <configuration>
      <metaModelFile>${kevoree.metamodel.folder}/${kevoree.metamodel}</metaModelFile>
      <metaModelQualifiedName>org.kevoree</metaModelQualifiedName>
      <js>true</js>
    </configuration>
</execution>
<!-- ... -->
```

The **Java** version of the model is well generated with `org.kevoree` as package name.  
The **JS** version of the model is **wrongly** generated with `org` as package name.  

I doubt this is a feature. Looks a lot like a bug.

**Comment by gnain** [comment]
We tried to reproduce in the test project ```test/org.kevoree.modeling.test.kevoree``` but always get the same result in Java and JS
